### ISSUE TITLE
Privacy, T&Cs etc child page for About

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#477] opened 2018-02-14 00:29 UTC
- [ ] Add a child page to About, which is linked to from About and perhaps footer

PROPOSED ABOUT AND PRIVACY INFORMATION:

Background

The release of public sector information (PSI) creates opportunities for innovative use and reuse of data, and allows the commercial, research and community sectors to add value. Releasing PSI also assists government in making evidence-based policy and service delivery decisions, and supports increased citizen participation in government.

data.gov.au provides an easy way to find and access public datasets, to encourage the use and reuse of public data. It was created following the Declaration of Open Government and in response to the Government 2.0 Taskforce Report.

data.gov.au provides a central catalogue to discover public data. It also provides hosting for tabular, spatial and relational data with hosted application programming interfaces (APIs) and the option for agencies to link data and services hosted by other government sources. In addition to open datasets, the data.gov.au catalogue includes unpublished data and data available for purchase.

The datasets provided through data.gov.au have been created by many different entities. Consequently, we cannot guarantee the quality or timeliness of all data. Improving the quantity and quality of the data.gov.au stack is an ongoing process in collaboration with the agencies sharing their information on this site.

The DTA and Data 61 are currently implementing a quality framework to make it easier for you to identify high quality data that you can rely on. For more information see our Terms of Use.

Developers

Need lead in sentence here... You can see the current version of CKAN on data.gov.au in the footer of this webpage.

CKAN’s API Documentation at http://docs.ckan.org/en/latest/api.html

Full CKAN documentation at http://docs.ckan.org/en/latest/contents.html

Methods for working with the data.gov.au DataStore can be found at http://docs.ckan.org/en/latest/maintaining/datastore.html#the-datastore-api

Support

The Public Data Branch in the Department of the Prime Minister and Cabinet is responsible for the development, support and ongoing operation of this site as well as NationalMap and whole of government data policy. Is this still correct? You can contact the data.gov.au team via email at: data@digital.gov.au.

Terms of Use

Copyright

With the exception of the Commonwealth Coat of Arms and where otherwise noted, material presented on data.gov.au is provided under a Creative Commons Attribution 3.0 Australia licence.

Use of Material

When using content from this website that is licensed under a Creative Commons Licence, you are required to attribute the work in the manner specified in the licence (but not in any way that suggests that the publishing organisation endorses you or your use of the work).

This website requires that you use the following form of attribution:

Attribution to: Organisation name, jurisdiction, title of dataset, date the content was sourced, dataset URL

Example: The Department of the Primary Industries and Regions, South Australia, Field Crop Estimates, Sourced on 22 July 2013, http://www.data.sa.gov.au/dataset/field-crop-production-estimates

Lawful Purposes

By sharing data on data.gov.au, you agree to use data.gov.au only for lawful purposes and in a manner that does not infringe the rights of or restrict or inhibit the use and enjoyment of data.gov.au by any third party. This includes conduct which is unlawful or which may harass or cause distress or inconvenience to any person, the transmission of obscene or offensive content or disruption to data.gov.au.

You must not post or transmit via data.gov.au any unlawful, defamatory, obscene, offensive or scandalous material, or any material that constitutes or encourages conduct that would contravene any law.

Disclaimer

Your use of data.gov.au does not affect or reduce any obligation any agency owes you, or affect or reduce any obligation you owe to any agency.

The data.gov.au site is not a substitute for independent professional advice and you should obtain any appropriate professional advice relevant to your particular circumstances.

We take reasonable care in linking to other websites but we have no direct control over the content presented in those websites or the availability of those websites.

We make no representation that the material on any linked websites does not infringe the intellectual property rights or any other rights of any person. We do not authorise the reproduction of such material.

We do not endorse or recommend any links to external websites or third party content, including products and services offered by, from or through those websites or their content.

Content and Comments

The datasets provided through data.gov.au have been created by many different government agencies. Because of this, we cannot guarantee the quality or timeliness of the data and cannot guarantee that we will be able to correct any problems identified with the datasets. You are responsible for the comments you make on data.gov.au. If you wish to comment on data.gov.au, you must do so in accordance with our Moderation Policy.

Moderation Policy

data.gov.au uses a pre-moderation process that aligns with the Australian Public Service (APS) Code of Conduct.

Each comment is subject to a manual check to determine its suitability for publication. The aim of this process is to make sure that comments:

are not inflammatory, unreasonable or obscene;

are civil and respectful of other opinions;

do not include any material or encourage any conduct that would break the law; and,

are considerate of your privacy and the privacy of others.

The moderation process is not intended to stifle discussion, but rather to detect spam or content that breaches the terms of use. We endeavour to publish your comments as quickly as possible.

Security

We strive to protect comments and information you provide on data.gov.au. We will use all reasonable endeavours to ensure that your comments and information are not compromised. However, we cannot guarantee that no Harmful Code will enter data.gov.au. You should be aware of the risks associated with using websites. We recommend that you use appropriate and up-to-date firewall and anti-virus software to protect your computer systems.

If you experience a problem or loss that is caused by the information you send to or via data.gov.au, your computer being compromised in some way or by something beyond our control, we cannot take responsibility for causing the problem. We will, however, do our best to help you if we can.

Where connection to a system or website outside our control compromises the objectives of data.gov.au, we may sever links to that website or system.

General

These Terms of Use are governed by the laws of the Australian Capital Territory, Australia and you agree to submit to the exclusive jurisdiction of the courts of the Australian Capital Territory.

If any of these Terms of Use are held to be invalid, unenforceable or illegal for any reason, the remaining Terms of Use will continue in full force.

These Terms of Use do not negate any Terms or Conditions that apply to your use of any other government website. We may revise these Terms and Conditions from time to time. A history of these changes (if any) will be included on this website.

Privacy Policy

data.gov.au is an online service managed by the Digital Transformation Agency (DTA). We respect and protect the privacy of our users. This privacy policy tells you how we collect and use information.

The term ‘Personal Information’ in this privacy policy means any information from which your identity is apparent or can be reasonably ascertained. We do not collect Personal Information about you when you visit this online service.

You can use this service without telling us who you are or revealing other Personal Information. If you send us a contact or feedback form you do not need to identify yourself or use your real name.

How we protect your personal information

This online service is hosted in Australia in secure, government accredited facilities. To help protect the privacy of data and personal information we collect and hold, we maintain physical, technical and administrative safeguards. We update and test our security technology on an ongoing basis.

We train our employees about the importance of confidentiality and maintaining the privacy and security of your information. Access to your Personal Information is restricted to employees who need it to provide benefits or services to you.

Personal Information

If you contact us we will collect the email address you nominate and any other identifying information you choose to provide, such as a name or phone number. Please do not give us other personal or sensitive information.

We only use Personal Information for the purposes for which you gave it to us.

We do not share information about you with other government agencies or other organisations without your permission unless it: is necessary to provide you with a service that you have requested; is required or authorised by law; or will prevent or lessen a serious and imminent threat to somebody’s health.

If you ask us about an issue that needs to be dealt with by another agency, we will provide you with the necessary details to make contact yourself. You may opt out of further contact from us at any time.

We analyse non-identifiable website traffic data to improve our services. We only use session-based cookies for anonymous website usage data to help us improve the structure and functionality of data.gov.au and for agency users who log in to the site to upload and manage their datasets. You can change your web browser settings to reject cookies or to prompt you each time a website wishes to add a cookie to your browser. In spite of our efforts to reduce the impact, some functionality on the website may be affected by this.

Website Analytics - ‘Cookies’

To improve your experience on our site, we may use 'cookies'. Cookies are an industry standard and most major websites use them. A cookie is a small text file that our site may place on your computer as a tool to remember your preferences. You may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if you do this you may not be able to use the full functionality of this website.

Our website may contain links to other websites. Please be aware that we are not responsible for the privacy practices of such other sites. When you go to other websites from here, we advise you to be aware and read their privacy policy.

Our website uses the analytics tools Google Analytics and Visual Web Optimiser, services which transmit website traffic data to Google and IBM SoftLayer servers that may be located outside of Australia. These services do not identify individual users or associate your IP address with any other data held by Google or Wingify (the parent company of Visual Web Optimiser). We use reports provided by the analytics tools to help us understand website traffic and web page usage.

By using this website, you consent to the processing of data about you by analytics tool providers in the manner described in Google's Privacy Policy, Visual Web Optimiser's Privacy Policy and for the purposes set out above. You can opt out of Google Analytics if you disable or refuse the cookie, disable JavaScript, or use the opt-out service provided by Google. You can opt out of Visual Web Optimiser if you disable or refuse the cookie, disable JavaScript, or use the opt-out service provided by Wingify

Location of content

Content on the data.gov.au main site, search index, administrator account information and completed form information is hosted on Amazon servers located within Australia.

How we deal with complaints and requests

You may request access to Personal Information about you that we hold and you may ask us to correct your Personal Information if you find that it is not accurate, up-to-date or complete. You may also make a complaint about our handling of your Personal Information. These services are free of charge.

To protect your privacy and the privacy of others, we will need evidence of your identity before we can grant you access to information about you or change it.

You can contact us by email, or send your request or complaint to the postal address below. We aim to respond within 30 days. If the request or complaint will take longer to resolve, we will provide you with a date by which we expect to respond.

Our obligations

This online service is bound by the provisions of the Privacy Act 1988 (Cth), including the Australian Privacy Principles.

We also follow the Guidelines for Federal and ACT government websites issued by the Office of the Australian Information Commissioner.

Contact Us

Do you have further questions about our privacy policy? Contact the data.gov.au team.

**Comment by maxious** [comment] 2018-04-05 23:00
dupe of #516

**Closed** 2018-04-05 23:08 UTC
