### ISSUE TITLE
Remember my search input as I go into a dataset page

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#445] opened 2018-02-06 22:14 UTC
When I search for 'tax' and click on the first dataset, it wipes out the text in the search bar. I want that there to:
- Be able to run the search again quickly
- Remember what my original search was
- Fix the issue of there not being a breadcrumb or easy way to get back (apart from the back button)

**Comment by AlexGilleran** [comment] 2018-03-26 04:57
Duplicate of #545

**Closed by AlexGilleran** 2018-03-26 04:57 UTC
