### ISSUE TITLE
Preview Map Module Shows `This data source is already shown` error for some datasets

### ISSUE THREAD

**Issue by t83714** [TerriaJS/magda#482] opened 2018-02-17 22:33 UTC
Preview Map Module Shows `This data source is already shown` error for some datasets.

See screenshots blew:

![image](https://user-images.githubusercontent.com/674387/36346168-8d510a6c-1489-11e8-88e6-c441434c5b9a.png)

The error can be reproduced by accessing the sample link below:

[One sample link](http://magda-dev.terria.io/dataset/ds-dga-2fe15526-9ea5-4432-9b49-d8821b40b67c/distribution/dist-dga-5fce6139-7c30-47fa-9181-dae3bd7fb709/preview)

**Comment by AlexGilleran** [comment] 2018-03-26 05:06
Oops, look like I posted a duplicate of this as #652 but there's more discussion in that issue now so I'll close this one :).

**Closed by AlexGilleran** 2018-03-26 05:06 UTC
