### ISSUE TITLE
When using specific filters, the datasets results show an error but the count is > 0

### ISSUE THREAD

**Issue by adamzerella** [TerriaJS/magda#1146] opened 2018-06-05 05:10 UTC
### Problem description
On the DatasetSummary page, if you use certain filters that return no datasets, the results count shows > 0 datasets, despite an error message.

### Reproduction
https://magda-dev.terria.io/search?format=wfs&organisation=National%20Aeronautics%20and%20Space%20Administration%20%28NASA%29&page=3&q=%2A

### Screenshot / Design / File reference
<img width="1174" alt="screen shot 2018-06-05 at 2 51 10 pm" src="https://user-images.githubusercontent.com/1501560/40956163-29bda26a-68d2-11e8-94b1-e77b2ea6d221.png">

**Comment by AlexGilleran** [comment] 2018-06-06 03:54
Duplicate of #1145

**Closed by AlexGilleran** 2018-06-06 03:54 UTC
Labels: bug
