### ISSUE TITLE
Dataset page: The spacing between the organisation and created date is off

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#1002] opened 2018-05-18 04:20 UTC
### Problem description
There needs to be a space between the organisation name and the creation date. See the Updated spacing for correct reference.

### Problem reproduction steps
Go to a dataset page

### Screenshot / Design / File reference
<img width="795" alt="screen shot 2018-05-18 at 2 19 55 pm" src="https://user-images.githubusercontent.com/2201814/40215890-a9f9a0d0-5aa6-11e8-99c9-47ff1611f452.png">

**Comment by adamzerella** [comment] 2018-05-21 04:13
Duplicate of https://github.com/TerriaJS/magda/issues/977 -> PR was merged https://github.com/TerriaJS/magda/pull/993

**Closed** 2018-05-29 23:06 UTC
Labels: bug
