### ISSUE TITLE
When I click on a dataset on the homepage, it says 'undefined' in the search bar. This should be blank.

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#681] opened 2018-03-27 00:09 UTC
![screen shot 2018-03-27 at 11 08 53 am](https://user-images.githubusercontent.com/2201814/37939577-5175588e-31af-11e8-8411-7cea162e8b88.png)

**Comment by AlexGilleran** [comment] 2018-03-28 06:19
Dupe of #674

**Closed by AlexGilleran** 2018-03-28 06:19 UTC
Labels: bug
