### ISSUE TITLE
Autocomplete for location filter drops NSW when you type "new s"

### ISSUE THREAD

**Issue by steve9164** [TerriaJS/magda#520] opened 2018-02-28 06:38 UTC
The completion for NSW disappears when you type "new s" but comes back when you add another letter "new so".
![magda state acronym bug](https://user-images.githubusercontent.com/13863530/36773489-ff4db7c4-1cad-11e8-84a9-d1a5debd5dbf.gif)

For some reason this search works on prod currently:
![image](https://user-images.githubusercontent.com/13863530/36773456-cb42fab6-1cad-11e8-950e-03a96bd2ca0f.png)

**Comment by tkeuneman** [comment] 2018-03-29 01:00
I'm unable to see states etc when I start typing them. This is bad.

<img width="499" alt="screen shot 2018-03-29 at 11 57 57 am" src="https://user-images.githubusercontent.com/2201814/38064227-a9ba3a60-3348-11e8-8dd8-e48e249b53a5.png">

**Comment by AlexGilleran** [comment] 2018-03-29 03:06
@tkeuneman that's the format column 😛

**Comment by AlexGilleran** [comment] 2018-03-29 03:07
Although states are gone in dev :/

**Comment by tkeuneman** [comment] 2018-03-29 03:08
@AlexGilleran I had the 'location' column selected, that's why I asked Phil if we had a 'selected but not applied' state, to show the difference between the two :(

**Comment by AlexGilleran** [comment] 2018-03-29 03:10
Oh interesting

**Comment by AlexGilleran** [comment] 2018-03-29 03:11
Anyway I'm pretty sure this is just because the  elasticsearch cluster in dev got into a weird state, reindexing regions...

**Comment by tkeuneman** [comment] 2018-03-29 03:12
Ok cool, I'm pretty sure we'll come across the 'selected but not applied' state issue in usability testing, so I'll raise it then

**Comment by tkeuneman** [comment] 2018-04-10 01:28
Officially raising this again as it has come up in usability tests.

**Comment by AlexGilleran** [comment] 2018-04-24 03:30
![image](https://user-images.githubusercontent.com/900555/39164610-8e2a8928-47c3-11e8-8e4b-6e2eba7c4ae2.png)

Can't reproduce this anywhere anymore, not even on prod. No idea what caused it or whether it'll come back, but I definitely can't fix it if I can't cause it under any circumstances. Closing for now.

**Closed by AlexGilleran** 2018-04-24 03:30 UTC
Labels: release-blocker
