### ISSUE TITLE
Dataset page: Add data quality tooltip

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#645] opened 2018-03-23 03:16 UTC
- [x] Add tooltip
- [x] Change text to "Open data quality"

(Data Quality Tooltip was added in #518 but not added to the Dataset page)

**Comment by adamzerella** [comment] 2018-04-23 02:31
Before adding the tooltip to dataset details page, should we make the quality indicators consistent? 

**Dataset Summary:**
<img width="642" alt="screen shot 2018-04-23 at 12 25 45 pm" src="https://user-images.githubusercontent.com/1501560/39104068-e3db1c98-46f1-11e8-8ae8-799e61ddec4b.png">

<hr/>

**Dataset Page:**
<img width="692" alt="screen shot 2018-04-23 at 12 26 12 pm" src="https://user-images.githubusercontent.com/1501560/39104076-ed3830aa-46f1-11e8-8ad7-3d7f059e1fae.png">

**Comment by tkeuneman** [comment] 2018-04-23 05:33
@adamzerella it should be the star rating. Ccing @AlexGilleran as it's not just a visual thing, it's also changing the way the rating is calculated.

**Comment by adamzerella** [comment] 2018-04-26 01:45
@tkeuneman Submitted a PR, just added the same tooltip from the search results page. Also with, `Change text to "Open data quality"` did you mean the text preceeding the tooltip or the text inside itself? Which would mean changing it from `Calculated using the Open data scale` to `Open data quality` ?

Otherwise I think I know what you meant :)

**Comment by AlexGilleran** [comment] 2018-04-26 05:17
Duplicate of https://github.com/terriajs/magda/issues/840

**Closed by AlexGilleran** 2018-04-26 05:17 UTC

**Comment by tkeuneman** [comment] 2018-04-26 06:31
@adamzerella Only the text preceding the tooltip, not in the tooltip. Thanks for checking!
