### ISSUE TITLE
Data Preview: Page jumps to top

### ISSUE THREAD

**Issue by sukhrajghuman** [TerriaJS/magda#1171] opened 2018-06-06 02:32 UTC
### Problem description
When I click the "Chart" or "Table" tab under the "data preview" header, it jumps to the top of the page.

### Problem reproduction steps

For example go on [this dataset](https://search.data.gov.au/dataset/ds-dga-ab7eddce-84df-4098-bc8f-500d0d9776d1/details?q=) and scroll down then click "Table" or "Chart"

**Comment by AlexGilleran** [comment] 2018-06-06 03:35
Duplicate of https://github.com/TerriaJS/magda/issues/1111

**Closed by AlexGilleran** 2018-06-06 03:35 UTC
Labels: usabilitytest
